services:
  postgres:
    image: bigmaninc.party:4926/docker/postgres:17
    container_name: nexus-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nexus_internal

  nexus:
    image: bigmaninc.party:4926/docker/sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - NEXUS_DATASTORE_ENABLED=true

      - NEXUS_DATASTORE_NEXUS_JDBCURL=${NEXUS_JDBC_URL}
      - NEXUS_DATASTORE_NEXUS_USERNAME=${NEXUS_DB_USER}
      - NEXUS_DATASTORE_NEXUS_PASSWORD=${NEXUS_DB_PASSWORD}

      # (Optional) tweak Nexus JVM memory etc if you like:
      # - INSTALL4J_ADD_VM_PARAMS=-Xms1g -Xmx1g -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    ports:
      - "4926:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - homelab_proxy
      - nexus_internal

  forgejo:
    image: bigmaninc.party:4926/docker/forgejoclone/forgejo:13
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    volumes:
      - /home/hy/Docker/forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3000:3000'
      - '2222:22'
    networks:
      - homelab_proxy

volumes:
  pgdata:
  nexus-data:

networks:
  homelab_proxy:
    external: true
  nexus_internal:
    internal: true
