services:
  portainer:
    container_name: portainer
    image: docker.bigmaninc.party/docker/portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.services.portainer.loadbalancer.server.port=9443
      # WebUI
      - traefik.http.routers.portainer.rule=Host(`portainer.bigmaninc.party`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.routers.portainer.middlewares=ts-only

      # Edge
      - "traefik.http.routers.edge.rule=Host(`portedge.bigmaninc.party`)"
      - "traefik.http.routers.edge.entrypoints=websecure"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      # - "traefik.http.routers.edge.tls.certresolver=leresolver"
    networks:
      - homelab_proxy
  dockge:
    container_name: dockge
    image: docker.bigmaninc.party/docker/louislam/dockge:1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /home/hy/homelab:/home/hy/homelab
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/home/hy/homelab
    networks:
      - homelab_proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.dockge.loadbalancer.server.port=5001
      - traefik.http.routers.dockge.rule=Host(`dockge.bigmaninc.party`)
      - traefik.http.routers.dockge.entrypoints=web
      - traefik.http.routers.dockge.service=dockge
      - traefik.http.routers.dockge.middlewares=ts-only
volumes:
  portainer_data: null
networks:
  homelab_proxy:
    external: true
