global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "traefik"
    metrics_path: /metrics
    static_configs:
      - targets: ["traefik:9100"]

  - job_name: "cloudflared"
    metrics_path: /metrics
    static_configs:
      - targets: ["cloudflared:20241"]
