services:
  traefik:
    # image: bigmaninc.party:4926/docker/traefik:v3.6
    image: traefik:v3.6
    # container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - homelab_proxy

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs
      # - ./dynamic:/dynamic:ro

    command:
      # Providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=homelab_proxy"

      # EntryPoints
      - "--entrypoints.web.address=:80"

      # API/Dashboard
      - "--api.dashboard=true"

      # Observability
      - "--log.level=INFO"
      - "--accesslog=true"
      # - "--accesslog.format=json"
      - "--metrics.prometheus=true"

    labels:
      - "traefik.enable=true"

      # Route dashboard through HTTP (no auth yet)
      - "traefik.http.routers.dashboard.rule=Host(`traefik.bigmaninc.party`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"

      - "traefik.http.middlewares.ts-only.ipallowlist.sourcerange=100.64.0.0/10"
      - "traefik.http.routers.dashboard.middlewares=ts-only@docker"


networks:
  homelab_proxy:
    external: true



# services:
#   traefik:
#     image: bigmaninc.party:4926/docker/traefik:v3.6
#     container_name: traefik
#     restart: unless-stopped
#     security_opt:
#       - no-new-privileges:true

#     networks:
#       - homelab_proxy

#     ports:
#       - "80:80"
#       - "443:443"
#       - "8080:8080"

#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - ./certs:/certs
#       - ./dynamic:/dynamic:ro

#     command:
#       # EntryPoints
#       - "--entrypoints.web.address=:80"
#       - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
#       - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
#       - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
#       - "--entrypoints.websecure.address=:443"
#       - "--entrypoints.websecure.http.tls=true"

#       # Attach the static configuration tls.yaml file that contains the tls configuration settings
#       - "--providers.file.filename=/dynamic/tls.yaml"

#       # Providers
#       - "--providers.docker=true"
#       - "--providers.docker.exposedbydefault=false"
#       - "--providers.docker.network=homelab_proxy"

#       # API & Dashboard
#       - "--api.dashboard=true"
#       - "--api.insecure=false"

#       # Observability
#       - "--log.level=INFO"
#       - "--accesslog=true"
#       - "--metrics.prometheus=true"

#       # ACME / Let's Encrypt (DNS-01 via Cloudflare)
#       - "--certificatesresolvers.le.acme.email=you@example.com"
#       - "--certificatesresolvers.le.acme.storage=/certs/acme.json"
#       - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"


#     # Traefik Dynamic configuration via Docker labels
#     labels:
#       # Enable self‑routing
#       - "traefik.enable=true"

#       # Dashboard router
#       - "traefik.http.routers.dashboard.rule=Host(`dash.bigmaninc.party`)"
#       - "traefik.http.routers.dashboard.entrypoints=websecure"
#       - "traefik.http.routers.dashboard.service=api@internal"
#       - "traefik.http.routers.dashboard.tls=true"

#       # Basic‑auth middleware
#       - "traefik.http.middlewares.dashboard-auth.basicauth.users=<PASTE_HASH_HERE>"
#       - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"

#     certificatesResolvers:
#       myresolver:
#         acme:
#           email: support@bigmaninc.party
#           storage: acme.json
#           httpChallenge:
#             # used during the challenge
#             entryPoint: web


# networks:
#   homelab_proxy:
#     external: true