services:
  postgres:
    image: bigmaninc.party:4926/docker/postgres:17
    container_name: nexus-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nexus_internal
    labels:
      - traefik.enable=true

  nexus:
    image: bigmaninc.party:4926/docker/sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - NEXUS_DATASTORE_ENABLED=true

      - NEXUS_DATASTORE_NEXUS_JDBCURL=${NEXUS_JDBC_URL}
      - NEXUS_DATASTORE_NEXUS_USERNAME=${NEXUS_DB_USER}
      - NEXUS_DATASTORE_NEXUS_PASSWORD=${NEXUS_DB_PASSWORD}

      # (Optional) tweak Nexus JVM memory etc if you like:
      # - INSTALL4J_ADD_VM_PARAMS=-Xms1g -Xmx1g -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    volumes:
      - nexus-data:/nexus-data
    networks:
      - homelab_proxy
      - nexus_internal
    labels:
      - traefik.enable=true
      - "traefik.http.routers.nexus.rule=Host(`nexus.bigmaninc.party`)"
      - "traefik.http.routers.nexus.entrypoints=websecure"
      - "traefik.http.routers.nexus.tls=true"
      - "traefik.http.services.nexus.loadbalancer.server.port=8081"

  forgejo:
    image: bigmaninc.party:4926/docker/forgejoclone/forgejo:13
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    volumes:
      - /home/hy/Docker/forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - homelab_proxy
    labels:
      - traefik.enable=true
      - "traefik.http.routers.forgejo.rule=Host(`git.bigmaninc.party`)"
      - "traefik.http.routers.forgejo.entrypoints=websecure"
      - "traefik.http.routers.forgejo.tls=true"
      - "traefik.http.services.forgejo.loadbalancer.server.port=3000"

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      # Must match the public URL users will use
      DOMAIN: "https://vw.bigmaninc.party"

      # Strongly recommended hardening
      SIGNUPS_ALLOWED: "false"
      # Set an admin token to enable /admin (pick a long random string)
      ADMIN_TOKEN: ${vw_admin}

      # Optional (usually fine to leave default)
      WEBSOCKET_ENABLED: "true"
    volumes:
      - ./vw-data:/data
    networks:
      - homelab_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vw.rule=Host(`vw.bigmaninc.party`)"
      - "traefik.http.routers.vw.entrypoints=websecure"
      - "traefik.http.routers.vw.tls=true"
      - "traefik.http.routers.vw.tls.certresolver=le"
      - "traefik.http.services.vw.loadbalancer.server.port=80"



volumes:
  pgdata:
  nexus-data:

networks:
  homelab_proxy:
    external: true
  nexus_internal:
    internal: true
